```{r regression single, echo=FALSE, results="asis"}
library(xtable)
lm.cyl<-lm(mpg~cyl,data=mtcars)
print(xtable(lm.cyl),comment=F)

lm.disp<-lm(mpg~disp,data=mtcars)
print(xtable(lm.disp),comment=F)

lm.hp<-lm(mpg~hp,data=mtcars)
print(xtable(lm.hp),comment=F)

lm.drat<-lm(mpg~drat,data=mtcars)
print(xtable(lm.drat),comment=F)

lm.wt<-lm(mpg~wt,data=mtcars)
print(xtable(lm.wt),comment=F)

lm.qsec<-lm(mpg~qsec,data=mtcars)
print(xtable(lm.qsec),comment=F)

lm.vs<-lm(mpg~vs,data=mtcars)
print(xtable(lm.vs),comment=F)

lm.am<-lm(mpg~am,data=mtcars)
print(xtable(lm.am),comment=F)

lm.gear<-lm(mpg~gear,data=mtcars)
print(xtable(lm.gear),comment=F)

lm.carb<-lm(mpg~carb,data=mtcars)
print(xtable(lm.carb),comment=F)
```

```{r regression multi, echo=FALSE, results="asis"}
library(MASS)
scope=list(upper=~cyl+disp+hp+drat+wt+qsec+vs+am+gear+carb)
initial=lm(mpg~1,data=mtcars)
step<-stepAIC(initial,scope,direction="forward")

lm.final<-lm(mpg~wt+qsec+am,data=mtcars)
lm.multi<-lm(mpg~cyl+disp+hp+drat+wt+qsec+vs+am+gear+carb,data=mtcars)

lm.multi<-lm(mpg~wt+qsec+am,data=mtcars)
```


